@ stdcall SetThreadErrorMode(long ptr)
@ stdcall VerifyVersionInfoW(ptr long int64)
@ stdcall AppPolicyGetWindowingModel(ptr ptr)
@ stdcall WaitOnAddress(ptr ptr long long)
@ stdcall WakeByAddressSingle(ptr)